rvm:
  - 2.3

env:
  - FOO=foo
  - FOO=bar

script: echo $FOO

jobs:
  include:
    - stage: deploy
      script: echo Deploy
      # Keep in mind to overwrite these here
      rvm: 2.3
      env: FOO=foo

addons:
  homebrew:
    brewfile: ./Brewfile.travis
    update: true